Add missing syntax render functions to TextRenderer
The following code currently leads to errors such as `TypeError: this.renderer.listitem is not a function`:

```javascript
marked(text, { renderer: new marked.TextRenderer });
```

This change provides a fix for those errors.